
server:
  port: 8081
spring:
  application:
    name: ${microservice.user.application.name}
  datasource:
    url: ${microservice.user.datasource.url}
    driver-class-name: ${microservice.user.datasource.driver-class-name}
    username: ${microservice.user.datasource.username}
    password: ${microservice.user.datasource.password}
  jpa:
    database-platform: ${microservice.user.jpa.database-platform}
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  config:
    import: optional:configserver:http://localhost:8888  
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka 
      
logging:
  config: ${microservice.log.config}
    
    

  